### PR TITLE
A minor bug fix, some simplification, remove support for Emacs < 24

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Comment by immerrr** [comment]
Hi Reuben! Glad to see you! Happy New Year!

CI has been working suboptimally lately, but I haven't had much chance to look into it. Hopefully I'll get to it this month. Did you get to check what are the failures and are they somehow related to the changes?

**Comment by rrthomas** [comment]
25 test failures seems to be a "normal" current result.

However, I've made the entire build on some older Emacs versions with my removal of compatibility code. This is strange, because the comments in the code I removed only mentioned compatibility for Emacs < 24.1, and 24.1 is the earliest version tested by Travis.

However, I find that `cl-labels` was introduced in 24.3. 24.3 was introduced nearly 5 years ago (March 2013), and is the version in the current oldest Ubuntu LTS release (14.04). Would it therefore be acceptable to drop support for Emacs < 24.3? In any case, I've pushed a `travis.yml` that does this to my PR.

**Comment by rrthomas** [comment]
I did a more thorough investigation: on current master, 22 tests fail. My removal of Emacs < 24 compatibility made 3 more tests fail, so I removed that commit from this pull request, leaving just my bug fixes. The tests that still fail are the same as those currently failing on master, so you may want to fix those failures first…

**Comment by immerrr** [comment]
Great, thank you. There's some work on making test runs work in a different issue/PR, I guess I need to make it work beforehand.

**Comment by immerrr** [comment]
Please, rebase your PR onto master, the failures should be fixed now.

**Comment by rrthomas** [comment]
Done. Looks good now (with just one check left to complete!).

**Comment by immerrr** [comment]
Merged, thank you!

**Comment by rrthomas** [comment]
Great, will now have a look at my other patch.

**Pull request merged**
